### PR TITLE
Update messages.coffee

### PR DESCRIPTION
**Pull request by fugawee**
Adding Polyp Canty

### CODE REVIEW

**Comment by suranc** [comment]
This doesn't work.  You should upload to imgur or a similar service that slack will unfurl.  Considering the link is from Slack itself it may unfurl it, but that is not a persistent link and it's already 404 not found.  Also, the image hosting service needs to allow arbitrary url arguments be passed so I can pass ?MMSS to allow for multiple unfurls an hour.  

In short, just upload the image to imgur and update the link...

**Comment by fugawee** [comment]
Changed the url to https://drive.google.com/open?id=0BzyfDcxT-CN0bmNaOENZak9NalU

**Comment by suranc** [comment]
That link does not unfurl properly.  You need to use a service that lets you link directly to the image, and will accept an arbitrary ?1234 argument at the end of the URL.  I recommend imgur as imgur does not delete images after 30 days like a lot of services.

**Comment by fugawee** [comment]
But isn't imgur open to the public?  I wouldn't want Polyp Canty stumbling upon it lol

**Comment by suranc** [comment]
All images must be public, I'm not going to setup some sort of authentication to see the image that we'll have to track separately, or worse, make this repository private.  I really don't think that would work anyways without a lot of effort, as the simplicity of this relies on slack automatically unfurling direct image links.

**Comment by suranc** [comment]
The image you posted seems public as well, unless you shared it to my google account or something.

**Comment by fugawee** [comment]
It's public to only those who have the url.  Eh, you can cancel the pull request.

**Pull request closed without merging**
